# Generated by Django 4.0.5 on 2022-06-20 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('상의', '상의'), ('하의', '하의'), ('신발', '신발'), ('악세서리', '악세서리')], max_length=20),
        ),
    ]
